name = "nv-pu-sa"
pages_build_output_dir = "./public"

[vars]
ADMIN_USER = "admin"
ADMIN_PASS = "admin123"

# Cloudflare Pages D1 绑定请在 Pages Dashboard -> Settings -> Functions -> D1 Database Bindings 进行绑定 (Variable name: DB)
